local M = {
	--SCENES
	LOAD_SCENE = "LOAD_SCENE",
	UNLOAD_SCENE = "UNLOAD_SCENE",
	--SOUNDS
	PLAY_SFX = "PLAY_SFX",
	PLAY_MUSIC = "PLAY_MUSIC",
	STOP_MUSIC = "STOP_MUSIC",
	--
	LOAD_SAHUR = "LOAD_SAHUR",
	LOAD_PATAPIM = "LOAD_PATAPIM",
	LOAD_CAPPUCINO = "LOAD_CAPPUCINO",
	CHARACTER_LOADED = "CHARACTER_LOADED",
	--BATTLE
	PLAYER_HURT = "PLAYER_HURT",
	ENEMY_HURT = "ENEMY_HURT",
	TRIGGER_SKILL = "TRIGGER_SKILL",
	--EFFECT
	PLAY_EFFECT_ON_ENEMY = "PLAY_EFFECT_ON_ENEMY",
	PLAY_EFFECT_ON_PLAYER = "PLAY_EFFECT_ON_PLAYER",
	SHAKE_EFFECT = "SHAKE_EFFECT",
}

return M