local M = {
	--debug
	SLOW_MOTION = "SLOW_MOTION",
	--SCENES
	PAUSE = "PAUSE",
	RESUME = "RESUME",
	CHANGE_SCENE = "CHANGE_SCENE",
	LOAD_SCENE = "LOAD_SCENE",
	UNLOAD_SCENE = "UNLOAD_SCENE",
	BACK_TO_MENU = "BACK_TO_MENU",
	--SETTINGS
	LANG_CHANGED = "LANG_CHANGED",
	DISABLE_SFX = "DISABLE_SFX",
	ENABLE_SFX = "ENABLE_SFX",
	DISABLE_MUSIC = "DISABLE_MUSIC",
	ENABLE_MUSIC = "ENABLE_MUSIC",
	--SOUNDS
	PLAY_SFX = "PLAY_SFX",
	PLAY_MUSIC = "PLAY_MUSIC",
	FADE_OUT_MUSIC = "FADE_OUT_MUSIC",
	FADE_IN_MUSIC = "FADE_IN_MUSIC",
	STOP_MUSIC = "STOP_MUSIC",
	PLAY_CAST = "PLAY_CAST",
	STOP_CAST = "STOP_CAST",
	PLAY_CHAT_SFX = "PLAY_CHAT_SFX",
	STOP_CHAT_SFX = "STOP_CHAT_SFX",
	--TUTORIAL
	SHOW_TUTORIAL = "SHOW_TUTORIAL",
	HIDE_TUTORIAL = "HIDE_TUTORIAL",
	--AD
	SHOW_FAILED_PANEL = "SHOW_FAILED_PANEL",
	HIDE_FAILED_PANEL = "HIDE_FAILED_PANEL",
	--
	ENEMY_ENTER = "ENEMY_ENTER",
	--
	SET_PLAYER_MOD = "SET_PLAYER_MOD",
	LOAD_SAHUR = "LOAD_SAHUR",
	LOAD_PATAPIM = "LOAD_PATAPIM",
	LOAD_CAPPUCINO = "LOAD_CAPPUCINO",
	CHARACTER_LOADED = "CHARACTER_LOADED",
	--BATTLE
	REVIVE = "REVIVE",
	PLAYER_HURT = "PLAYER_HURT",
	ENEMY_HURT = "ENEMY_HURT",
	PLAYER_HEAL = "PLAYER_HEAL",
	ENEMY_HEAL = "ENEMY_HEAL",
	TRIGGER_SKILL = "TRIGGER_SKILL",
	ADD_RAGE = "ADD_RAGE",
	ADD_CP = "ADD_CP",
	PAY_RESOURCE_COST = "PAY_RESOURCE_COST",
	PLAYER_START_CASTING = "PLAYER_START_CASTING",
	PLAYER_FINISH_CASTING = "PLAYER_FINISH_CASTING",
	ENEMY_START_CASTING = "ENEMY_START_CASTING",
	ENEMY_FINISH_CASTING = "ENEMY_FINISH_CASTING",
	INTERRUPT_PLAYER_CASTING = "INTERRUPT_PLAYER_CASTING",
	INTERRUPT_ENEMY_CASTING = "INTERRUPT_ENEMY_CASTING",
	START_CHAT = "START_CHAT",
	END_CHAT = "END_CHAT",
	START_PLAYER_ULTI_CASTING = "START_PLAYER_ULTI_CASTING",
	END_PLAYER_ULTI_CASTING = "END_PLAYER_ULTI_CASTING",
	START_ENEMY_ULTI_CASTING = "START_ENEMY_ULTI_CASTING",
	END_ENEMY_ULTI_CASTING = "END_ENEMY_ULTI_CASTING",
	--GAMEOVER
	PLAYER_DIE = "PLAYER_DIE",
	ENEMY_DIE = "ENEMY_DIE",
	--EFFECT
	ENRAGE_EFFECT_ON_PLAYER = "ENRAGE_EFFECT_ON_PLAYER",
	ENRAGE_EFFECT_ON_ENEMY = "ENRAGE_EFFECT_ON_ENEMY",
	PLAY_PARTICLE_ON_ENEMY = "PLAY_PARTICLE_ON_ENEMY",
	PLAY_PARTICLE_ON_PLAYER = "PLAY_PARTICLE_ON_PLAYER",
	PLAY_EFFECT_ON_ENEMY = "PLAY_EFFECT_ON_ENEMY",
	PLAY_EFFECT_ON_PLAYER = "PLAY_EFFECT_ON_PLAYER",
	SHAKE_EFFECT = "SHAKE_EFFECT",
	PLAYER_SHOOT_PROJECTILE = "PLAYER_SHOOT_PROJECTILE",
	ENEMY_SHOOT_PROJECTILE = "ENEMY_SHOOT_PROJECTILE",
	FLASH_EFFECT = "FLASH_EFFECT",
	--
	STOP_ROCKET = "STOP_ROCKET"
}

function M.getStartCastingEvent(enemyCasted)
	return enemyCasted and M.ENEMY_START_CASTING or M.PLAYER_START_CASTING
end

function M.getFinishCastingEvent(enemyCasted)
	return enemyCasted and M.ENEMY_FINISH_CASTING or M.PLAYER_FINISH_CASTING
end

function M.getHurtEvent(enemyCasted) 
	if enemyCasted then
		return M.PLAYER_HURT
	else
		return M.ENEMY_HURT
	end
end

function M.getStartUltiCastingEvent(enemyCasted) 
	return enemyCasted and M.START_ENEMY_ULTI_CASTING or M.START_PLAYER_ULTI_CASTING
end

function M.getEndUltiCastingEvent(enemyCasted) 
	return enemyCasted and M.END_ENEMY_ULTI_CASTING or M.END_PLAYER_ULTI_CASTING
end

function M.getEffectEvent(enemyCasted) 
	if enemyCasted then
		return M.PLAY_EFFECT_ON_PLAYER
	else
		return M.PLAY_EFFECT_ON_ENEMY
	end
end

function M.getParticleEvent(enemyCasted) 
	if enemyCasted then
		return M.PLAY_PARTICLE_ON_PLAYER
	else
		return M.PLAY_PARTICLE_ON_ENEMY
	end
end

function M.getProjectileEvent(enemyCasted)
	if enemyCasted then
		return M.ENEMY_SHOOT_PROJECTILE
	else
		return M.PLAYER_SHOOT_PROJECTILE
	end
end

return M