local M = {
	--debug
	SLOW_MOTION = "SLOW_MOTION",
	--SCENES
	LOAD_SCENE = "LOAD_SCENE",
	UNLOAD_SCENE = "UNLOAD_SCENE",
	--SOUNDS
	PLAY_SFX = "PLAY_SFX",
	PLAY_MUSIC = "PLAY_MUSIC",
	STOP_MUSIC = "STOP_MUSIC",
	--
	SET_PLAYER_MOD = "SET_PLAYER_MOD",
	LOAD_SAHUR = "LOAD_SAHUR",
	LOAD_PATAPIM = "LOAD_PATAPIM",
	LOAD_CAPPUCINO = "LOAD_CAPPUCINO",
	CHARACTER_LOADED = "CHARACTER_LOADED",
	--BATTLE
	PLAYER_HURT = "PLAYER_HURT",
	ENEMY_HURT = "ENEMY_HURT",
	TRIGGER_SKILL = "TRIGGER_SKILL",
	ADD_RAGE = "ADD_RAGE",
	PAY_RESOURCE_COST = "PAY_RESOURCE_COST",
	--EFFECT
	PLAY_PARTICLE_ON_ENEMY = "PLAY_PARTICLE_ON_ENEMY",
	PLAY_PARTICLE_ON_PLAYER = "PLAY_PARTICLE_ON_PLAYER",
	PLAY_EFFECT_ON_ENEMY = "PLAY_EFFECT_ON_ENEMY",
	PLAY_EFFECT_ON_PLAYER = "PLAY_EFFECT_ON_PLAYER",
	SHAKE_EFFECT = "SHAKE_EFFECT",
	PLAYER_SHOOT_PROJECTILE = "PLAYER_SHOOT_PROJECTILE",
	ENEMY_SHOOT_PROJECTILE = "ENEMY_SHOOT_PROJECTILE",
}

function M.getHurtEvent(enemyCasted) 
	if enemyCasted then
		return M.PLAYER_HURT
	else
		return M.ENEMY_HURT
	end
end

function M.getEffectEvent(enemyCasted) 
	if enemyCasted then
		return M.PLAY_EFFECT_ON_PLAYER
	else
		return M.PLAY_EFFECT_ON_ENEMY
	end
end

function M.getParticleEvent(enemyCasted) 
	if enemyCasted then
		return M.PLAY_PARTICLE_ON_PLAYER
	else
		return M.PLAY_PARTICLE_ON_ENEMY
	end
end

function M.getProjectileEvent(enemyCasted)
	if enemyCasted then
		return M.ENEMY_SHOOT_PROJECTILE
	else
		return M.PLAYER_SHOOT_PROJECTILE
	end
end

return M